### ISSUE TITLE
data by invokeScript isn’t available by AP

### ISSUE THREAD

**Issue by AlekseiPupyshev** [wavesplatform/data-service#185]
Issue Report - data by **invokeScript** isn’t available by API:

https://wavesexplorer.com/testnet/address/3N4GgQWCckqUn1H9y8rNRyCXZPkgKTNKznT

data: several key-value pairs generated by call of invokeScript

dapp address: 3N4GgQWCckqUn1H9y8rNRyCXZPkgKTNKznT

Results doesn’t contain invokeScript data
https://api.testnet.wavesplatform.com/v0/docs/#/transactions/searchTxsData

Issue 1: SCRIPT-transactions cannot be found by GET /transactions/data/

After generation of several “classical” data transactions - all transactions and data were found by API

Issue 2: SCRIPT-transactions cannot be found by GET /transactions/all/
https://api.testnet.wavesplatform.com/v0/docs/#/transactions/searchTxsAll

Issue 3: script and invokescript transactions are invisible for GET /transactions/all/ for sender (invokeTransaction caller)
https://wavesexplorer.com/testnet/address/3Mt9UZD5iajUxsfo7aTw11F8GTNQZHJKAUP

P.S.: Interesting that **waves explorer** works fine and I can see all key-value data pairs even generated by invokeScript

**Comment by xrtm000** [comment]
@AlekseiPupyshev, hi!
Script transactions are currently not supported by data service.
You can fetch invoke script transactions using Waves node API.
https://testnode1.wavesnodes.com/api-docs/index.html#!/transactions/addressLimit_1

**Comment by dvshur** [comment]
@AlekseiPupyshev, hi, thank you for using our service and giving feedback. As for the issues:
>Issue 1: SCRIPT-transactions cannot be found by GET /transactions/data/

That is expected. That endpoint only returns data-transactions (type 12).

>Issue 2: SCRIPT-transactions cannot be found by GET /transactions/all/
>Issue 3: script and invokescript transactions are invisible for GET /transactions/all/ for sender 

We'll support them shortly in `/transactions/all` endpoint.

>I can see all key-value data pairs even generated by invokeScript

That functionality is more advanced, since InvokeScript transaction body itself does not contain state changes it caused. We're currently working on an API that will show state changes by each transaction, so it will be possible in the near future (q2, most likely).

**Comment by AlekseiPupyshev** [comment]
Thank you! 
Actually, I was mislead by this "data service".
Yes, you are right my solution for getting key-value data is the same api to node:
https://testnodes.wavesnodes.com/api-docs/index.html#!/addresses/getData
But it wasn't obvious!

anyway, there is a lot of limitations like max-100 recent transactions, so I hope Data Service will be much more helpful for advanced queries

Best,
