### ISSUE TITLE
Install package /v0/docs/

### ISSUE THREAD

**Issue by wavespay** [wavesplatform/data-service#215]
Hello!
Please tell me the repository of the documentation Swagger program located on the link https://api.wavesplatform.com/v0/docs and how to install it?

**Comment by dvshur** [comment]
Hi, we published the docs in #216. Now in `develop` branch, but we're going to merge to `master` this week after testing.

**Comment by dvshur** [comment]
Now in `master`. I hope it helps, but if you have any questions, feel free to ask. Closing the issue for now.
