### ISSUE TITLE
[BUG] - Data Inconsistancy

### ISSUE THREAD

**Issue by justjamesdev** [wavesplatform/data-service#298]
When calling the following endpoint the 'close' number is 2.55; 

https://api.wavesplatform.com/v0/candles/WAVES/6VFYAjvphuUyxmgPNAU1uEGcom8oLqJN4eu7jY2ihyV4?matcher=3P4vjfsebcfiv3oNTdFyXqGpFAnwY2c74HD&timeStart=1578484800000&interval=12h&timeEnd=1578562500000

```
{"__type":"list","data":[{"__type":"candle","data":{"time":"2020-01-08T12:00:00.000Z","open":2.55,"close":2.55,"high":2.6,"low":2.51,"volume":2576,"quoteVolume":6553.28,"weightedAveragePrice":2.54,"maxHeight":1875505,"txsCount":4}},{"__type":"candle","data":{"time":"2020-01-09T00:00:00.000Z","open":null,"close":null,"high":null,"low":null,"volume":null,"quoteVolume":null,"weightedAveragePrice":null,"maxHeight":null,"txsCount":0}}]}
```

But when I list transactions in date order decending the most recent tx price is 2.51

https://api.wavesplatform.com/v0/transactions/exchange?matcher=3P4vjfsebcfiv3oNTdFyXqGpFAnwY2c74HD&timeStart=1578484800000&timeEnd=1578562500000&sort=desc&limit=100

```
{"__type":"list","isLastPage":true,"lastCursor":"MjAyMC0wMS0wOFQxMjowMjoxNi43ODVaOjpIOW9Yd1cxNDhDc2JMc0ZqOG5yWGRuVUpxYUNlRUJMZUJXN014WlhTUUNweDo6ZGVzYw==","data":[{"__type":"transaction","data":{"id":"EqHxcWRJwZAAqNRqjS83ozkpAhgBqa6r48JSWDvS2FeR","timestamp":"2020-01-08T14:16:43.762Z","height":1875505,"type":7,"version":2,"proofs":["VCdNpbVhSpwWVCDiJPskp244zA2ynTjBNcA8YnndBUdikxHXgN98jujBEcynzdE3N5gMSpknAXv3o3MyrNs6cru"],"fee":0.003,"sender":"3P4vjfsebcfiv3oNTdFyXqGpFAnwY2c74HD","senderPublicKey":"4gHpbhVJeuHrb6yv5RuPYBEXn6MJdx4ZbjEqtmjx6mdQ","buyMatcherFee":0.003,"sellMatcherFee":0.003,"price":2.51,"am...
```

The expected result would be that the candles service returns the last trade price in this case with a close of 2.51

**Comment by dvshur** [comment]
Hi, @justjamesdev, thanks for the report. It's not immediately obvious what has happened, we'll investigate it further.

**Comment by justjamesdev** [comment]
Thanks! There's examples of this happening all the time, this was just one that is replicatable

**Comment by justjamesdev** [comment]
Closing as was never resolved
