### ISSUE TITLE
[BUG] Passing Build Issue

### ISSUE THREAD

**Issue by xucito** [wavesplatform/data-service#308]
**Describe the bug**
When running the repository from tag v0.28.0 there are test issues and build issues.

Am I doing something wrong?
![image](https://user-images.githubusercontent.com/36687889/73810548-4abf5e00-47f0-11ea-98da-b5fdd0868b9a.png)

**To Reproduce**
1. Download git
2. run`npm install`
3. run `npm run buiild` 
3. See error

**Expected behavior**
Project can build
Tests all pass

**Please complete as much of the following information as you can:**
 - Git version v0.28.0

**Comment by dvshur** [comment]
Hi, @xucito. First of all, it seems your first try — `npm run build` — had actually been a success, since no errors were shown.

On the second try, I believe you're trying to build with a global `tsc` command, which uses global TypeScript build. My guess would be a TypeScript version incompatibility. But still, `npm run build` seems to have succeeded, why bother with the global TS?

**Comment by xucito** [comment]
Sorry the screenshot is a bit misleading `npm run build` has the same the errors however it is running the external shell.

After checking the version you were correct, the global typescript version was 3.1.1 which has some compatibility issues. After updating it most the build issues disappeared however there are still two typing issues.

![image](https://user-images.githubusercontent.com/36687889/73833111-da7e0000-4822-11ea-8c7b-650a68179bab.png)

**Comment by BlackTurtle123** [comment]
> Hi, @xucito. First of all, it seems your first try — `npm run build` — had actually been a success, since no errors were shown.
> 
> On the second try, I believe you're trying to build with a global `tsc` command, which uses global TypeScript build. My guess would be a TypeScript version incompatibility. But still, `npm run build` seems to have succeeded, why bother with the global TS?

The docker container provided in the project doesn't seem to build either.
I tried latest tag and I tried latest code.

**Comment by xucito** [comment]
Found out that it is an issue with later version of typescript.

Changed `"typescript": "^3.6.3"` to ` "typescript": "3.6.3"` in package.json and regenerating package-lock.json fixes the issue.

**Comment by dvshur** [comment]
Sorry for long response, but I'm glad it all worked out for you! Strange thing about Typescript though, we'll look into it at some point. Looks like we can consider this issue resolved, but If you have any more questions, feel free to reopen or create a new one.
