### ISSUE TITLE
[BUG] Candles not calculating? 

### ISSUE THREAD

**Issue by justjamesdev** [wavesplatform/data-service#323]
**Describe the bug**
The following URL shows transactions happening today (24th Sept)

https://api.wavesplatform.com/v0/transactions/exchange?matcher=3PJe4pG5fRwZh5EPwvtyQHCMpG7NVp7HBwh&amountAsset=5siW5tqvYLnfgeXttU7F9dZ3xrE8UHVtpqT9Ye71GBuJ&sort=desc&limit=100

 and when reviewing candles service for the same time period all is null; 

https://api.wavesplatform.com/v0/candles/6VFYAjvphuUyxmgPNAU1uEGcom8oLqJN4eu7jY2ihyV4/5siW5tqvYLnfgeXttU7F9dZ3xrE8UHVtpqT9Ye71GBuJ?matcher=3PJe4pG5fRwZh5EPwvtyQHCMpG7NVp7HBwh&timeStart=1598270400000&interval=12h

**To Reproduce**
Review both URLs

**Expected behavior**
There should be candles generated for the dates where transactions happened. And the value of those should be correct. 

Matcher: 3PJe4pG5fRwZh5EPwvtyQHCMpG7NVp7HBwh

**Comment by justjamesdev** [comment]
Theres still this issue happening every day. Has anyone had a chance to look into whats causing this?

**Comment by Jlewka** [comment]
@justjamesdev Hey!

1) sorry for taking so long to answer;

2) your queries does not correlate with each other: exchanges query looking for txs with 5siW5tqvYLnfgeXttU7F9dZ3xrE8UHVtpqT9Ye71GBuJ as the amount asset, but candles query looking for candles with 6VFYAjvphuUyxmgPNAU1uEGcom8oLqJN4eu7jY2ihyV4 as the amount asset, and 5siW5tqvYLnfgeXttU7F9dZ3xrE8UHVtpqT9Ye71GBuJ as the price asset. If you query the candles with the reversed pair (5siW5tqvYLnfgeXttU7F9dZ3xrE8UHVtpqT9Ye71GBuJ/6VFYAjvphuUyxmgPNAU1uEGcom8oLqJN4eu7jY2ihyV4), you will see the correct candles
