### ISSUE TITLE
Docs loads but everything returns 404.

### ISSUE THREAD

**Issue by viraladmin** [wavesplatform/data-service#330]
The comment says it all. Manually compiled. Docs load but nothing seems to work other than the ability to visit the page. All commands return 404.

**Comment by Jlewka** [comment]
Hey, @viraladmin 

Can you show your request and the appropriate response with?

**Comment by viraladmin** [comment]
At the moment neither the docs nor the api service seem to properly work. 

http://api.tactoken.io:3000/ << this loads the api. As can be seen this works fine. 

Nothing else however seems to. 

Trying with something basic:

http://api.tactoken.io:3000/assets/WAVES returns internal server error.

**Comment by viraladmin** [comment]
http://api.tactoken.io:3000/assets/TAC 

This returns from the data service perfectly fine, but when using the docs...

http://api.tactoken.io

if I try to use the assetID sectoin - it returns 404. (tried with WAVES and with TAC)

http://api.tactoken.io/v0/assets/TAC - returns 404
http://api.tactoken.io/v0/assets/WAVES - returns 404
http://api.tactoken.io/assets/WAVES - returns 404
http://api.tactoken.io/assets/TAC - returns 404. 

So it seems its working, its just the doc interface that is broken. 

I did a local npm build on main source but the only option for the docs is the docker build. Perhaps this relates?

Any help would be great.

**Comment by Jlewka** [comment]
To run the data-service and the documentation at the same time, you have to has an instance of gateway (i.e. nginx), that would be route the `/docs` requests to the documentation service and all the other - to the data-service.

**Comment by viraladmin** [comment]
Any chance you have a nginx conf example? Trying to wrap my head around how to set it up. I am semi-fluent with nginx (thats what I am currently using to forward front end to backend ports), just a matter of understanding exactly how this setup would look.

**Comment by viraladmin** [comment]
I got that sorted so it runs from /docs/ however it still returns a 404 on all commands. 

It seems commands all tack a /v0/ on them causing them to fail.

For example: http://api.tactoken.io/assets/TAC -- returns correctly
However: http://api.tactoken.io/v0/assets/TAC -- does not and causes the docs to return a 404.
