### ISSUE TITLE
[FEATURE REQUEST] Support tx 18 InvokeScript the same way as regular invokeScript

### ISSUE THREAD

**Issue by christopheSeeka** [wavesplatform/data-service#365]
**Is your feature request related to a problem? Please describe.**
Hello,

Our web applications are using api.wavesplatform.com/v0/ to list all recent actions of our dapps or users in several places.
With the new tx 18 release, we started to implement MetaMask support but realized that invoke made with metamask then don't show up in all these place relying on invoke history (based on /transactions/invoke-script).

**Describe the solution you'd like**
Since an invoke script is an invoke script, it would make sens for us that they show in invoke-script end point (maybe optional), regardless if the call was made with MetaMask or a native waves signing tool. It is still an invoke call to a dapp generating the same result from the same action.

**Describe alternatives you've considered**
If this don't make enough sense then at least a separated endpoint for 18 that allow the same filtering as regular invoke-script so we could call both and merge the results and then get all invoke script calls for a specific dapp and / or callable

**Comment by dvshur** [comment]
Hi, @christopheSeeka!

What you're asking for looks quite logical, I think it's a good idea. I've added a task to our backlog. Unfortunately, this is not our main priority at the moment, and I cannot vouch for any time estimates.

If you would like to help with implementing the feature, feel free to open a PR.

Thank you for your feedback and for using the Data Service.

**Comment by dvshur** [comment]
Hi again, @christopheSeeka!

I've added basic support for ETH transactions in https://github.com/wavesplatform/data-service/pull/386.

They do not have a detailed payload, like Waves Node. Full parsing is quite complex to implement, and we only have limited time.

But they already can be filtered by `type=invocation | transfer` or `function` name. Also, they will appear in /transactions/all endpoint.

**Comment by christopheSeeka** [comment]
Hi! thank you for the update, I think it should be enough for our needs, I'll give it a try :)
